### PR TITLE
test: Add right bitshift tests

### PR DESCRIPTION
**Pull request by Syndamia**
Add tests for `>>`. Note that **all** of them should be successful if our implementation was feature-complete.

### CODE REVIEW

**Comment by Syndamia** [comment]
Currently **BLOCKED** due to an upstream bug

**Comment by Syndamia** [comment]
Upstream bug report: https://github.com/noir-lang/noir/issues/6201

**Comment by Syndamia** [comment]
Upstream fixed the right shift bugs, and as of today's repo sync, `>>` works on `nargo execute`.

The force-push is me rebasing this branch. I executed all right shift tests and they all produced the same value as expected in `Prover.toml`. Thought a check by someone else will be appreciated.

**Comment by nickysn** [comment]
Unfortunately, there's another test that fails now: `plonky2_prove_success/right_shift_unsigned_const`:
```
error: Internal Consistency Evaluators Errors: 

                    This is likely a bug. Consider opening an issue at https://github.com/noir-lang/noir/issues
  ┌─ /home/nickysn/code/repos/metacraft-labs/noir/test_programs/plonky2_prove_success/right_shift_unsigned_const/src/main.nr:1:1
  │
1 │ fn main(
  │ - ICE: \"PLONKY2 backend ICE error: mismatching arg types: Integer(16, false) and Field; instr: \\\"Binary(Binary { lhs: Id(0), rhs: Id(2), operator: Div })\\\"\"
  │
  = Call stack:
    1. /home/nickysn/code/repos/metacraft-labs/noir/test_programs/plonky2_prove_success/right_shift_unsigned_const/src/main.nr:5:10

Error: Aborting due to 1 previous error
```
Possibly something has changed inside the compiler, that makes it fail, since I assume it used to work before. So, it's a known failure and per our policy, should be moved to plonky2_prove_crash, until we fix it in the plonky2 backend.

**Comment by Syndamia** [comment]
Good catch, I had forgotten there was a test inside `plonky2_prove_success`

**Comment by nickysn** [comment]
LGTM

**Pull request merged**
