### PR TITLE
fix(plonky2_gen): Internal inconsistency when acessing a single-element array

### PR DESCRIPTION
**Pull request by Syndamia**
In [PR 78](https://github.com/blocksense-network/noir/pull/78) I added three (`prove_failure`) tests, showing that if we have a single-element array in Prove.toml and try to acess it (on a valid index), `nargo prove` will result in an error.

With this PR the issue is resolved and the tests are moved to `prove_success`.

The fundamental problem was that inside `from_noir_type` there was code, where if we had the (notation-ally equivalent) type to `[T; 1]`, the function would instead return the type `T` (but with `[T; 2]` it would correctly return `[T; 2]`).
I don't personally find reason in that choice, and all (other) tests pass after the change, so I'm confident this is the final solution to the issue.

### CODE REVIEW

**Review by Aristotelis2002 — APPROVED** [review]
Great job on finding and fixing the bug! I ran the tests locally an they succeed.

**Comment by Syndamia** [comment]
I will wait on a review from @smanilov since the original implementation was from him. There is a possibility this breaks some case he knows (but didn't make a test for).

**Comment by smanilov** [comment]
> Great job on finding and fixing the bug! I ran the tests locally and they succeed.

Thanks, I was going to ask for that.

**Comment by smanilov** [comment]
> I will wait on a review from @smanilov since the original implementation was from him. There is a possibility this breaks some case he knows (but didn't make a test for).

Thanks for the foresight. Let's go ahead with this change and see later if it breaks something. If the tests pass, then we consider it an improvement. If it breaks something, than the fault is in that tests were missing.

**Pull request merged**
